<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use AppBundle\Model\AddressDataInterface;

/**
 * AddressDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressDataRepository extends \Doctrine\ORM\EntityRepository
{
	public function save(AddressDataInterface $adata) {
		$em = $this->getEntityManager();
        $em->persist($adata);
        $em->flush();
    }
}
