<?php

namespace AppBundle\Repository;

/**
 * AddressDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressDataRepository extends \Doctrine\ORM\EntityRepository
{
}
