<?php

namespace AppBundle\Repository;

/**
 * ParcelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcelRepository extends \Doctrine\ORM\EntityRepository
{
}
