<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use AppBundle\Model\ParcelInterface;

/**
 * ParcelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcelRepository extends \Doctrine\ORM\EntityRepository
{
	public function save(ParcelInterface $parcel) {
		$em = $this->getEntityManager();
        $em->persist($parcel);
        $em->flush();
    }
}
