<?php

namespace AppBundle\Repository;

/**
 * PostmanTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostmanTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
