<?php

namespace AppBundle\Repository;

use AppBundle\Model\PostmanInterface;

/**
 * PostmanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostmanRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(PostmanInterface $postman) {
		$em = $this->getEntityManager();
        	$em->persist($postman);
        	$em->flush();
    }
}
