<?php

namespace AppBundle\Repository;

use AppBundle\Model\PostmanInterface;

/**
 * PostmanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostmanRepository extends \Doctrine\ORM\EntityRepository
{
    public function find($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AppBundle:Postman p WHERE p.id =' . $id )
            ->getResult();
    }
    public function save(PostmanInterface $postman) {
		$em = $this->getEntityManager();
        	$em->persist($postman);
        	$em->flush();
    }
}
