<?php

namespace AppBundle\Repository;


use AppBundle\Model\PostmanTravelInterface;

/**
 * PostmanTravelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostmanTravelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedById()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:PostmanTravel p ORDER BY p.id ASC'
            )->getResult();
    }

    public function find($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:PostmanTravel p WHERE p.id =' .$id
            )->getResult();
    }

    public function save(PostmanTravelInterface $postmantravel) {
		$em = $this->getEntityManager();
        	$em->persist($postmantravel);
        	$em->flush();
    } 
}
