<?php

namespace AppBundle\Repository;

/**
 * PostmanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostmanRepository extends \Doctrine\ORM\EntityRepository
{
}
