<?php

namespace PostmanBundle\Repository;

use PostmanBundle\Model\PostmanInterface;

/**
 * PostmanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostmanRepository extends \Doctrine\ORM\EntityRepository
{    
    public function edit($request, $postman)
    {
        //$form = $this->buildForm(PostmanType::class, $request);
        $postman->setFirstName($request->request->get('first_name'));
        $postman->setLastName($request->request->get('last_name'));
        $postman->setPhone($request->request->get('phone'));
        $postman->setEmail($request->request->get('email'));
        $postman->setCity($request->request->get('city'));
        $postman->setPassword($request->request->get('password'));
        return $postman;
    }
}
