postman_travel:
    type: rest
    resource: 'AppBundle\Controller\PostmanTravelController'
    
address_data:
    type: rest
    prefix: /v1
    resource: 'AppBundle\Controller\AddressDataController'
    name_prefix: adr_1_ # naming collision
